account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import *

app_name = "account"

urlpatterns = [
    path("",landing,name="landing"),
    path("home/",home,name="home"),
    path("signup/",SignUpView.as_view(),name="signup"),
    path("login/",LoginView.as_view(),name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/home/"), name="logout"),
]

campgrounds/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import *

app_name = "campgrounds"

urlpatterns = [
    path("individual/<int:pk>/",campground,name="individual"),
    path("comment/<int:pk>",comment,name="comment"),
    path("add/",AddCampground.as_view(),name="add")
]

yelpcamp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('account.urls'), name='landing'),
    path('campgrounds/', include('campgrounds.urls'), name='campgrounds'),
    path('admin/', admin.site.urls),
]

campgrounds/models.py
from django.db import models
from account.models import User
from django.utils import timezone
import math

# Create your models here.

class Campground(models.Model):
    name = models.CharField(max_length=100,blank=False,null=False)
    price = models.CharField(max_length=4)
    image = models.CharField(max_length=300)
    description = models.CharField(max_length=400)
    user = models.ForeignKey(User,related_name='submitted_by',on_delete=models.PROTECT)
    address = models.CharField(max_length=100)

class Comment(models.Model):
    comment = models.CharField(max_length=300,blank=False,null=False)
    campground = models.ForeignKey(Campground, verbose_name=("Campground"), on_delete=models.CASCADE)
    user = models.ForeignKey(User, verbose_name="Created By", on_delete=models.PROTECT)
    created_at = models.DateTimeField("Created at", auto_now=True, auto_now_add=False)

    def whenpublished(self):
        now = timezone.now()
        
        diff= now - self.created_at

        if diff.days == 0 and diff.seconds >= 0 and diff.seconds < 60:
            seconds= diff.seconds
            
            if seconds == 1:
                return str(seconds) +  "second ago"
            
            else:
                return str(seconds) + " seconds ago"

            

        if diff.days == 0 and diff.seconds >= 60 and diff.seconds < 3600:
            minutes= math.floor(diff.seconds/60)

            if minutes == 1:
                return str(minutes) + " minute ago"
            
            else:
                return str(minutes) + " minutes ago"



        if diff.days == 0 and diff.seconds >= 3600 and diff.seconds < 86400:
            hours= math.floor(diff.seconds/3600)

            if hours == 1:
                return str(hours) + "hr ago"

            else:
                return str(hours) + "hrs ago"

        # 1 day to 30 days
        if diff.days >= 1 and diff.days < 30:
            days= diff.days
        
            if days == 1:
                return str(days) + " day ago"

            else:
                return str(days) + " days ago"

        if diff.days >= 30 and diff.days < 365:
            months= math.floor(diff.days/30)
            

            if months == 1:
                return str(months) + " month ago"

            else:
                return str(months) + " months ago"


        if diff.days >= 365:
            years= math.floor(diff.days/365)

            if years == 1:
                return str(years) + " year ago"

            else:
                return str(years) + " years ago"

campgrounds/forms.py
from django import forms
from .models import *

class CampgroundForm(forms.ModelForm):
    name = forms.CharField(label='Camp Name',widget=forms.TextInput(attrs={'class': 'yelp-input','placeholder':'Seven Sisters Waterfall'}),required=True)
    price = forms.CharField(label='Price', widget=forms.TextInput(attrs={'class': 'yelp-input','placeholder':'$149'}),required=True)
    image = forms.CharField(label='Image URL', widget=forms.TextInput(attrs={'class': 'yelp-input','placeholder':'https://i.pinimg.com/originals/c1/be/5c/c1be5c01ff0b6168a5d16e96e0fce8de.jpg'}),required=True)
    description = forms.CharField(label='Description', widget=forms.Textarea(attrs={'class': 'yelp-input','placeholder':"The Seven Sisters is the 39th tallest waterfall in Norway. The 410-metre tall waterfall consists of seven separate streams,and the tallest of the seven has a free fall that measures 250 metres. The waterfall is located along the Geirangerfjorden in Stranda Municipality in Møre og Romsdal county, Norway."}))
    address = forms.CharField(label='Description',widget=forms.TextInput(attrs={'class':'yelp-input','placeholder':'Seve Sisters Waterfall'}))

    class Meta:
        model = Campground
        fields = ('name','price','image','description','address',)

class CommentForm(forms.ModelForm):
    
    comment = forms.CharField(label='Description', widget=forms.Textarea(attrs={'class': 'yelp-input','maxlength':300,'placeholder':"This was probably the best camp i've visited this past year, definitely recommend visiting any time soon."}))

    class Meta:
        model = Comment
        fields = ("comment",)

campgrounds/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.edit import FormView
from .models import *
from .forms import *
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.urls import reverse


class AddCampground(LoginRequiredMixin, FormView):
    template_name = 'campgrounds/add.html'
    form_class = CampgroundForm
    success_url = '/home/'
    login_url = '/login/'

    def form_valid(self, form):
        form.save(commit=False)
        user = self.request.user
        form.instance.user_id = user.id
        form.save()
        return super().form_valid(form)

def campground(request,pk):
    camp = get_object_or_404(Campground,pk=pk)
    comments = Comment.objects.filter(campground_id=pk).order_by("-id")[:3]
    return render(request, 'campgrounds/individual.html', {"camp": camp,'comments':comments})


@login_required
def comment(request,pk):
    camp = get_object_or_404(Campground,pk=pk)
    user = request.user
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.instance
            comment.campground = camp
            comment.user = user
            comment.created_at = timezone.now()
            form.save()
            return HttpResponseRedirect('/campgrounds/individual/'+str(pk))
        else:
            return render(request,'campgrounds/comment.html',{'form':form})
    form = CommentForm()
    return render(request,'campgrounds/comment.html',{'form':form})

templates/campgrounds/add.html
{% extends 'menu.html' %}

{% block content %}

<div class="uk-margin">

    <div class="uk-width-xlarge uk-margin-auto">

        <form method="post">
            {% csrf_token %}
            <fieldset class="uk-fieldset">
        
                <h2 class="uk-text-left">Add New Campground</h2>
        
                <div class="uk-margin">
                    <p class="yelp-label">Campground Name</p>
                    {{form.name}}
                </div>
        
                <div class="uk-margin">
                    <p class="yelp-label">Price</p>
                    {{form.price}}
                </div>

                <div class="uk-margin">
                    <p class="yelp-label">Image</p>
                    {{form.image}}
                </div>

                <div class="uk-margin">
                    <p class="yelp-label">Location</p>
                    {{form.address}}
                </div>

                <div class="uk-margin">
                    <p class="yelp-label">Description</p>
                    {{form.description}} 
                </div>

                <button type="submit" class="uk-button uk-button-secondary yelp-btn">Add New Campground</button>

            </fieldset>
        </form>
    </div>


</div>

{% endblock  %}

templates/campgrounds/comment.html
{% extends 'menu.html' %}

{% block content %}

<div class="uk-margin">

    <div class="uk-width-large uk-margin-auto">

        <form method="post">
            {% csrf_token %}
            <fieldset class="uk-fieldset">
        
                <h2 class="uk-text-left">Add New Comment</h2>

                <div class="uk-margin">
                    <p class="yelp-label">Description</p>
                    {{form.comment}}
                    {% for error in form.comment.errors %}
                    <p class="uk-text-meta uk-text-danger">{{error}}</p>
                    {% endfor %}
                    <button class="uk-button uk-button-secondary yelp-btn">Post Comment</button>
                </div>
        
            </fieldset>
        </form>
    </div>


</div>

{% endblock  %}

templates/campgrounds/individual.html
{% extends 'menu.html' %}
{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'css/bootstrap-grid.min.css' %}">
{% endblock  %}

{% block content %}

<div class="row">

    <div class="col uk-flex-first@l uk-flex-last">
        <div class="uk-card uk-card-small uk-card-default uk-padding-small camp-card uk-margin">
            <div class="uk-padding">
                <div class="mapouter">
                    <div class="gmap_canvas">
                        <iframe style="width:100%" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q={{camp.address|cut:" "}}&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-7">

        <div class="uk-card uk-card-small uk-card-default uk-padding-small camp-card uk-margin">

            <div class="uk-padding">

                <div class="uk-card-media-top">
                    <img src="{{camp.image}}" alt="">
                </div>
    
                <div class="uk-text-left">
                    <div class="uk-flex-inline uk-width-1-1 uk-flex-between uk-flex-middle">
                        <h3 class="camp-card-title">{{camp.name}}</h3>
                        <p class="uk-margin-small">$ {{camp.price}}/night</p>
                    </div>
                    <p class="camp-card-desc uk-margin-large-right@l">{{camp.description}}</p>
                    
                    <p class="uk-margin"><i>Submitted by {{camp.user.username|title}}</i></p>
                </div>

            </div>

        </div>


        <div class="uk-card uk-card-small uk-card-default uk-padding-small camp-card uk-margin" id="yelp-comment-section">

            <div class="uk-padding uk-margin-top uk-padding-remove-top">
                <ul class="uk-list uk-list-divider">

                    {% if comments %}
                        {% for comm in comments %}
                            <li>
                                <div class="uk-flex-inline uk-width-1-1 uk-flex-between uk-flex-middle">
                                    <h5 class="camp-card-title">{{comm.user.username|title}}</h5>
                                    {% comment %} <p>{{comm.created_at|timesince}} ago</p> {% endcomment %}
                                    <p>{{comm.whenpublished}}</p>
                                </div>

                                <p class="uk-margin-remove-top">{{comm.comment}}</p>
                            </li>
                        {% endfor %}
                    {% else %}
                            <li><p class="uk-text-muted uk-text-center">Be the first to comment.</p></li>
                    {% endif %}
                
                </ul>

                <div class="uk-text-right">

                    <a href="{% url 'campgrounds:comment' camp.id %}" class="uk-button uk-button-secondary yelp-btn yelp-btn-auto-width">
                        <svg class="uk-margin-small-right" width="24" height="25" viewBox="0 0 24 25" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <g clip-path="url(#clip0)">
                            <path d="M12 3.5C17.514 3.5 22 7.092 22 11.507C22 16.424 16.855 19.468 12.09 19.468C10.153 19.468 8.707 19.071 7.696 18.824C6.696 19.437 6.101 19.861 3.424 20.644C3.959 19.271 4.147 17.896 4.026 16.379C3.188 15.379 2.001 13.979 2.001 11.507C2 7.092 6.486 3.5 12 3.5ZM12 1.5C5.662 1.5 0 5.726 0 11.507C0 13.557 0.738 15.57 2.047 17.132C2.102 18.962 1.024 21.588 0.054 23.5C2.656 23.03 6.355 21.992 8.032 20.964C9.45 21.309 10.807 21.467 12.091 21.467C19.175 21.467 24.001 16.63 24.001 11.506C24 5.695 18.299 1.5 12 1.5ZM8.5 11.5C8.5 12.329 7.829 13 7 13C6.172 13 5.5 12.329 5.5 11.5C5.5 10.671 6.172 10 7 10C7.829 10 8.5 10.671 8.5 11.5ZM12 10C11.172 10 10.5 10.671 10.5 11.5C10.5 12.329 11.172 13 12 13C12.829 13 13.5 12.329 13.5 11.5C13.5 10.671 12.829 10 12 10ZM17 10C16.172 10 15.5 10.671 15.5 11.5C15.5 12.329 16.172 13 17 13C17.829 13 18.5 12.329 18.5 11.5C18.5 10.671 17.829 10 17 10Z" fill="white"/>
                            </g>
                            <defs>
                            <clipPath id="clip0">
                            <rect width="24" height="24" fill="white" transform="translate(0 0.5)"/>
                            </clipPath>
                            </defs>
                            </svg>
                            Leave a review
                    </a>

                </div>

            </div>

        </div>

    </div>

</div>


{% endblock %}