account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import *

app_name = "account"

urlpatterns = [
    path("",landing,name="landing"),
    path("home/",home,name="home"),
    path("signup/",SignUpView.as_view(),name="signup"),
    path("login/",LoginView.as_view(),name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page="/home/"), name="logout"),
]

campgrounds/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import *

app_name = "campgrounds"

urlpatterns = [
    path("individual/<int:pk>/",campground,name="individual"),
    path("comment/<int:pk>",comment,name="comment"),
    path("add/",AddCampground.as_view(),name="add")
]

yelpcamp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('', include('account.urls'), name='landing'),
    path('campgrounds/', include('campgrounds.urls'), name='campgrounds'),
    path('admin/', admin.site.urls),
]

templates/dashboard/home.html
{% extends 'menu.html' %}
{% load static %}

{% block content %}

<div class="uk-section uk-padding-large" style="background-color: #f9f6f1;">
        <div style="max-width: 400px;">

            <h2 style="font-weight: 800;">Welcome to YelpCamp!</h2>
            <p class="uk-margin-small">View our hand-picked campgrounds from all over the world, or add your own.</p>

            <form method="get">
                <div class="uk-margin">
                    <div>

                        <div class="uk-inline" >
                            <span class="uk-form-icon" uk-icon="icon: search"></span>
                            {{filter.form.name}}

                        </div>
                        <button class="uk-button uk-button-secondary uk-margin-small">Search</button>

                    </div>
                    <a class="uk-link-muted" href="{% url 'campgrounds:add' %}">Or add your own campground</a>
                </div>
            </form>

        </div>
</div>

<div class="uk-section uk-margin-large-bottom">

    <div class="uk-child-width-1-2@s uk-child-width-1-2@m uk-child-width-1-3@l " uk-grid uk-height-match="target: > div > .uk-card">

        {% for camp in camps %}
        <div>

            <div class="uk-card uk-card-small uk-card-default uk-padding-small camp-card">

                <div class="uk-card-media-top">
                    <img src="{{camp.image}}" alt="">
                </div>

                <div class="body" >
                    <p class="camp-card-title">{{camp.name}}</p>
                    <p class="camp-card-desc uk-margin-large-right">{{camp.description}}</p>
                    <div class="place-btn" style="margin-top: auto;">
                    <a href="{% url 'campgrounds:individual' camp.id %}"><button class="uk-button uk-button-default camp-card-btn">View Campground</button></a>
                    </div>
                </div>

            </div>

        </div>
        {% endfor %}

    </div>
</div>

{% endblock %}

templates/dashboard/landing.html
{% extends 'divider.html' %}
{% load static %}


{% block first %}

    <div class="img-mobile" style="background-image: url({% static 'assets/hero_mob.jpg' %});"></div>
    <h1 class="hero-title">Explore the best camps on Earth.</h1>
    <p class="hero-desc uk-width-large">YelpCamp is a curated list of the best camping spots on
        Earth. Unfiltered and unbiased reviews.</p>

    <ul class="uk-list uk-margin-small">
        <li>
            <span class="uk-margin-small-right">
                <img src="{% static 'assets/dot.svg' %}" />
            </span>
            Add your camping suggestions
        </li>

        <li>
            <span class="uk-margin-small-right">
                <img src="{% static 'assets/dot.svg' %}" />
            </span>
            Leave reviews and experiences
        </li>

        <li>
            <span class="uk-margin-small-right">
                <img src="{% static 'assets/dot.svg' %}" />
            </span>
            See locations for all camps
        </li>
    </ul>

    <a href="{% url 'account:home' %}" class="uk-button uk-button-secondary yelp-btn yelp-btn-auto-width">View Campgrounds</a>

    <p>Partnered with:</p>
    <ul class="uk-iconnav">
        <li>
            <img src="{% static 'assets/airbnb.svg' %}" alt="Airbnb Logo" />
        </li>

        <li>
            <img src="{% static 'assets/booking.svg' %}"  alt="Booking Logo"/>
        </li>

        <li>
            <img src="{% static 'assets/plum.svg' %}" alt="Plum Guide Logo" />
        </li>
    </ul>

{% endblock %}

{% block second %}

<div class="side-img"
    style="height: 100%; background-size: cover;width: 100%;background-image: url({% static 'assets/herodesk.jpg' %});">
</div>

{% endblock second %}